spring:
  data:
    redis:
      host: 10.0.1.169    # ← EC2 내부 Redis IP
      port: 6379

external:
  fastapi:
    home-present-url: http://fastapi-app:8000/users/homePresent
    survey-recommend-url: http://fastapi-app:8000/survey/result
    keyword-recommend-url: http://fastapi-app:8000/keywords/result

