spring:
  data:
    redis:
      host: localhost
      port: 6379

external:
  fastapi:
    home-present-url: http://localhost:8000/users/homePresent
    survey-recommend-url: http://localhost:8000/survey/result
    keyword-recommend-url: http://localhost:8000/keywords/result
